# Generated by Django 3.2.12 on 2022-03-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staff_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_feedback',
            name='feedback_reply',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
